In [1]:
import pandas as pd
import numpy as np

In [8]:
np.array([1,2,3]*15).reshape(15,3).T

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [16]:
temp = np.array([[1,2,3],[4,2,3],[7,2,3]])
temp

array([[1, 2, 3],
       [4, 2, 3],
       [7, 2, 3]])

In [17]:
np.array(temp[:,0].tolist()*15).reshape(15,3).T

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [2]:
test_matrix = np.array([[1,0,0],[2,1,5],[3,0,0]])
np.where(test_matrix[:,1]==0)

(array([0, 2], dtype=int64),)

In [4]:
index = np.where(test_matrix[:,1]==0)[0]

In [5]:
for each in index:
    print(each)

0
2
