In [10]:
import numpy as np

In [4]:
l1 = np.array([0,0,0,0,0])
l1[2:]

array([0, 0, 0])

In [5]:
l1[2:] = l1[2:]+1

In [6]:
l1

array([0, 0, 1, 1, 1])

In [13]:
l2 = np.array([0,1,2]*15).reshape(15,3).T

In [14]:
l2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [35]:
l2.reshape(1,-1).tolist()[0]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [41]:
l = np.array([0,0,0,1])
l.any() == 0

False

In [43]:
np.array([[0,0,0],[1,1,1],[2,2,2],[4,4,4]]).reshape(4,-1)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [4, 4, 4]])

In [11]:
test = np.array([[0,1,2],[3,0,5],[0,0,8]])

In [18]:
np.where(test<=0)

AttributeError: 'tuple' object has no attribute 'tolist'

In [20]:
nrow =np.where(test<=0)[0]
ncol=np.where(test<=0)[1]
for row, col in zip(nrow,ncol):
    print(row*3+col+1)

1
5
7
8


In [21]:
2670-1860-47*50

-1540

In [22]:
2570-1920-51*50

-1900