In [10]:
import numpy as np
import pandas as pd

In [4]:
l1 = np.array([0,0,0,0,0])
l1[2:]

array([0, 0, 0])

In [5]:
l1[2:] = l1[2:]+1

In [6]:
l1

array([0, 0, 1, 1, 1])

In [13]:
l2 = np.array([0,1,2]*15).reshape(15,3).T

In [14]:
l2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [35]:
l2.reshape(1,-1).tolist()[0]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [41]:
l = np.array([0,0,0,1])
l.any() == 0

False

In [43]:
np.array([[0,0,0],[1,1,1],[2,2,2],[4,4,4]]).reshape(4,-1)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [4, 4, 4]])

In [11]:
test = np.array([[0,1,2],[3,0,5],[0,0,8]])

In [18]:
np.where(test<=0)

AttributeError: 'tuple' object has no attribute 'tolist'

In [20]:
nrow =np.where(test<=0)[0]
ncol=np.where(test<=0)[1]
for row, col in zip(nrow,ncol):
    print(row*3+col+1)

1
5
7
8


In [21]:
2670-1860-47*50

-1540

In [22]:
2570-1920-51*50

-1900

In [1]:
import numpy as np

In [41]:
status = np.array([[1,0,8],[0,-2,5]])

In [26]:
status[list(np.where(status[:,2]<=0)[0])] = 0

In [43]:
status

array([[ 1,  0,  8],
       [ 0, -2,  5]])

In [42]:
list(np.where(status[list(np.where(status[:,1]<=0)[0]),2]>0)[0])

[0, 1]

In [2]:
import pandas as pd
import numpy as np

In [24]:
so_assign = pd.read_csv("../save_data/需求41供给11/400-0.25/assign_info/so_2.csv")
fbfs_assign = pd.read_csv("../save_data/需求41供给11/400-0.25/assign_info/fbfs_2.csv")
dp_assign = pd.read_csv("../save_data/需求41供给11/400-0.25/assign_info/dp_2.csv")

In [25]:
so_assign.drop('assign_t',inplace=True,axis=1)

In [26]:
fbfs_assign.drop(['assign_t','cruising_t'],inplace=True,axis=1)
dp_assign.drop(['assign_t','cruising_t'],inplace=True,axis=1)

In [27]:
so_assign = pd.merge(so_assign,fbfs_assign,on='req_id',how='outer')
so_assign = pd.merge(so_assign,dp_assign,on='req_id',how='outer')

In [28]:
so_assign

req_id  space_num_x  pl_num_x  space_num_y  pl_num_y  space_num  pl_num
0      42.0          0.0       0.0         32.0       0.0       90.0     3.0
1     104.0          1.0       0.0         81.0       3.0       75.0     3.0
2     208.0          1.0       0.0          NaN       NaN        NaN     NaN
3     232.0          1.0       0.0          NaN       NaN        NaN     NaN
4      78.0          2.0       0.0         74.0       3.0       64.0     2.0
..      ...          ...       ...          ...       ...        ...     ...
397   113.0          NaN       NaN          NaN       NaN       89.0     3.0
398   138.0          NaN       NaN          NaN       NaN        4.0     0.0
399   205.0          NaN       NaN          NaN       NaN       75.0     3.0
400   283.0          NaN       NaN          NaN       NaN       43.0     1.0
401   350.0          NaN       NaN          NaN       NaN       30.0     0.0

[402 rows x 7 columns]

In [29]:
req_info = pd.read_csv("../需求分布/demand0607/400-0.25.csv")
req_info

Unnamed: 0  request_t  arrival_t  activity_t  leave_t  label  O  D  \
0             0        -27         17         344      361      0  1  0   
1             1         33         48        1301     1349      0  1  0   
2             2         64         89         301      390      0  0  0   
3             3        141        166        1334     1500      0  1  0   
4             4        192        202         825     1027      0  1  0   
..          ...        ...        ...         ...      ...    ... .. ..   
495         495       1397       1412          44     1456      1  0  1   
496         496       1374       1419          56     1475      1  1  1   
497         497       1398       1423          43     1466      1  0  1   
498         498       1398       1423          97     1520      1  0  1   
499         499       1401       1426         103     1529      1  1  0   

     new_label  revenue  req_id  
0            0      NaN       0  
1            0      NaN       1  
2            0      NaN       2  
3            0      NaN       3  
4            0      NaN       4  
..         ...      ...     ...  
495          1      NaN     495  
496          1      NaN     496  
497          1      NaN     497  
498          2      NaN     498  
499          2      NaN     499  

[500 rows x 11 columns]

In [30]:
def get_revenue(req_info):
    park_fee = 3 / 2  # 半个小时的费用
    charge_fee = [0, 0.7, 0.3]  # 每分钟的价格
    reserved_fee = 1  # 预约费用
    req_info['revenue'] = [(np.floor(req_info['activity_t'].iloc[i] / 15) * park_fee + (
            req_info['activity_t'].iloc[i] * (charge_fee[req_info['new_label'].iloc[i]])) + reserved_fee) for i in
                           range(len(req_info))]
    req_info['revenue_std'] = (req_info['revenue'] - min(req_info['revenue'])) / (
            max(req_info['revenue']) - min(req_info['revenue']))
    return req_info
req_info  = get_revenue(req_info)

In [32]:
req_info.drop('Unnamed: 0',inplace=True,axis=1)
req_info = pd.merge(req_info,so_assign,on='req_id',how='left')

In [33]:
req_info

request_t  arrival_t  activity_t  leave_t  label  O  D  new_label  \
0          -27         17         344      361      0  1  0          0   
1           33         48        1301     1349      0  1  0          0   
2           64         89         301      390      0  0  0          0   
3          141        166        1334     1500      0  1  0          0   
4          192        202         825     1027      0  1  0          0   
..         ...        ...         ...      ...    ... .. ..        ...   
495       1397       1412          44     1456      1  0  1          1   
496       1374       1419          56     1475      1  1  1          1   
497       1398       1423          43     1466      1  0  1          1   
498       1398       1423          97     1520      1  0  1          2   
499       1401       1426         103     1529      1  1  0          2   

     revenue  req_id  revenue_std  space_num_x  pl_num_x  space_num_y  \
0       34.0       0     0.215686         30.0       0.0         39.0   
1      130.0       1     0.843137         47.0       1.0          5.0   
2       31.0       2     0.196078         76.0       3.0         13.0   
3      133.0       3     0.862745         51.0       1.0         15.0   
4       83.5       4     0.539216         71.0       3.0         38.0   
..       ...     ...          ...          ...       ...          ...   
495     34.8     495     0.220915         23.0       0.0          NaN   
496     44.7     496     0.285621         26.0       0.0         31.0   
497     34.1     497     0.216340         56.0       1.0          NaN   
498     39.1     498     0.249020         37.0       0.0          NaN   
499     40.9     499     0.260784         69.0       2.0          NaN   

     pl_num_y  space_num  pl_num  
0         0.0       41.0     1.0  
1         0.0       38.0     0.0  
2         0.0        5.0     0.0  
3         0.0       16.0     0.0  
4         0.0        0.0     0.0  
..        ...        ...     ...  
495       NaN        NaN     NaN  
496       0.0       91.0     3.0  
497       NaN        NaN     NaN  
498       NaN        NaN     NaN  
499       NaN        NaN     NaN  

[500 rows x 17 columns]